//! The single bincode serialization seam for all on-disk binary formats.
//!
//! Every database row, blob and header that is not JSON goes through
//! [`bc_serialize`] / [`bc_deserialize`] — nothing else in the workspace may
//! call `bincode::` directly. This keeps the byte-level disk format anchored
//! in exactly one place:
//!
//! - **v1.3.0 swap**: the underlying crate moved bincode 1.3.3 → 2.0.x with
//!   `bincode::serde` + `config::legacy()`, which reproduces the bincode 1.x
//!   byte format exactly (fixint LE, u64 length prefixes, enum u8 variants).
//!   Byte parity with everything already written to disk is pinned by the
//!   golden fixtures in `database/bincode_golden.rs` (six types) and
//!   `application/src/service/sync/container.rs::bincode_golden` (sync
//!   fingerprint inputs, bincode 1.3.3-generated bytes). If a bincode 2.x
//!   upgrade turns those tests red, legacy disk rows would stop reading —
//!   evaluate disk compatibility in the same commit.
//! - **Future format migration** (e.g. postcard, the endgame for the
//!   RUSTSEC-2025-0141 unmaintained advisory): only this seam changes, plus
//!   a deliberate read-side migration — the golden fixtures define what
//!   "old bytes" mean.

use serde::{de::DeserializeOwned, Serialize};

/// Serialize `value` to bytes in the pinned legacy (bincode 1-compatible)
/// format. All on-disk binary rows/blobs go through this — see the module
/// docs for the golden-test contract.
pub fn bc_serialize<T: Serialize>(value: &T) -> Result<Vec<u8>, bincode::error::EncodeError> {
    bincode::serde::encode_to_vec(value, bincode::config::legacy())
}

/// Deserialize bytes previously written by [`bc_serialize`] (legacy
/// bincode 1-compatible format). Callers on the disk boundary must run
/// `database::check_encoded_blob_size` first, as before.
///
/// Takes [`DeserializeOwned`] because bincode 2's serde `decode_from_slice`
/// only supports owned values (all on-disk shapes here are owned structs).
pub fn bc_deserialize<T: DeserializeOwned>(bytes: &[u8]) -> Result<T, bincode::error::DecodeError> {
    bincode::serde::decode_from_slice(bytes, bincode::config::legacy()).map(|(v, _)| v)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrips_scalar_and_collection_shapes() {
        let value: (u64, Vec<String>, Option<i64>) =
            (42, vec!["a".to_string(), "日本".to_string()], Some(-7));
        let bytes = bc_serialize(&value).unwrap();
        let back: (u64, Vec<String>, Option<i64>) = bc_deserialize(&bytes).unwrap();
        assert_eq!(back, value);
    }
}
