//! Golden byte fixtures pinning the on-disk serialization format.
//!
//! **Provenance**: every `*_HEX` constant below was produced by **bincode
//! 1.3.3** on `main @ b9185a2` (v1.2.4) with `bincode::serialize` — captured
//! BEFORE the v1.3.0 bincode 1 → 2 dependency swap, while 1.3.3 was still on
//! the tree. The samples cover the §0 matrix: empty/`None` boundaries,
//! `i64::MIN`/`u64::MAX`/`usize::MAX` extremes, multi-byte UTF-8, and long
//! `Vec`s (257-byte pattern).
//!
//! **These tests are the legacy-compatibility tripwire.** If upgrading
//! bincode 2.x (or the `bc_serialize`/`bc_deserialize` config) makes any of
//! them red, the legacy byte semantics have drifted: on-disk rows written by
//! older app versions would stop reading back. Any such change MUST be
//! evaluated for disk compatibility in the same commit — either the config
//! is restored to byte-parity, or a read-side migration is designed and
//! shipped deliberately.
//!
//! The single serialization seam is [`crate::crypto::bc_serialize`] /
//! [`crate::crypto::bc_deserialize`] (bincode 2 serde bridge with
//! `config::legacy()`); a future postcard migration only changes that seam —
//! these fixtures are what proves the replacement is byte-safe.

use serde::de::DeserializeOwned;
use serde::Serialize;

use crate::crypto::{
    bc_deserialize, bc_serialize, AdaptiveParams, EncryptedData, VerificationData,
};
use crate::vault_header::VaultHeader;

use super::{Group, PasswordEntry, Settings};

// ---------------------------------------------------------------------------
// Fixtures (hex, generated by bincode 1.3.3 — see module docs)
// ---------------------------------------------------------------------------

/// `EncryptedData { nonce: [], ciphertext: [] }`
const ENCRYPTED_DATA_EMPTY_HEX: &str = "00000000000000000000000000000000";

/// `EncryptedData { nonce: 0x00..=0x0b, ciphertext: 257-byte (i*7 % 256) pattern }`
const ENCRYPTED_DATA_POPULATED_HEX: &str = "0c00000000000000000102030405060708090a0b010100000000000000070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2d9e0e7eef5fc030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c838a91989fa6adb4bbc2c9d0d7dee5ecf3fa01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd040b121920272e353c434a51585f666d747b828990979ea5acb3bac1c8cfd6dde4ebf2f900";

/// All-empty / all-`None` `PasswordEntry` (zero timestamps).
const PASSWORD_ENTRY_MINIMAL_HEX: &str = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

/// Fully populated `PasswordEntry`: UTF-8 ids/titles/tags, populated secret
/// blobs, tombstone + TOTP + group set.
const PASSWORD_ENTRY_FULL_UTF8_HEX: &str = "1400000000000000656e7472792d757569642de697a5e69cace8aa9e1100000000000000e6a087e9a2982d5469746c652df09f8e8b011a0000000000000068747470733a2f2f6578616d706c652e636f6d2fe8aaace6988e100000000000000075736572406578616d706c652e636f6d3000000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f012000000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f03000000000000000400000000000000776f726b0600000000000000e993b6e8a18c2b000000000000007461672d776974682d766572792d6c6f6e672d6e616d652d666f722d6c656e6774682d636f76657261676500f1536500000000d2f5536500000000010f1854650000000001070000000000000067726f75702d31011018546500000000011400000000000000000102030405060708090a0b0c0d0e0f10111213";

/// All-empty / all-`None` `Group`.
const GROUP_MINIMAL_HEX: &str =
    "000000000000000000000000000000000000000000000000000000000000000000";

/// `Group` with UTF-8 id/name, `created_at = i64::MIN`, tombstone `i64::MAX`.
const GROUP_FULL_EXTREMES_HEX: &str = "0f0000000000000067726f75702d757569642df09f8eaf1200000000000000e5b7a5e4bd9c2fe4b8aae4baba2d42616e6b000000000000008000f153650000000001ffffffffffffff7f";

/// `Settings::default()` (600s / 16 / all-true).
const SETTINGS_DEFAULT_HEX: &str = "580200000000000010000000000000000101010101";

/// `Settings` at `u64::MAX` / `usize::MAX` / all-false.
const SETTINGS_EXTREMES_HEX: &str = "ffffffffffffffffffffffffffffffff0000000000";

/// `VerificationData` with zero salt, default params, empty header blob.
const VERIFICATION_DATA_BASELINE_HEX: &str =
    "0000000000000000000000000000000000000100030000000400000000000000000000000000000000000000";

/// `VerificationData` with 0x00-0x0f salt, `u32::MAX` params, populated header.
const VERIFICATION_DATA_EXTREMES_HEX: &str = "000102030405060708090a0b0c0d0e0fffffffffffffffffffffffff0c00000000000000000102030405060708090a0b010100000000000000070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2d9e0e7eef5fc030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dce3eaf1f8ff060d141b222930373e454c535a61686f767d848b9299a0a7aeb5bcc3cad1d8dfe6edf4fb020910171e252c333a41484f565d646b727980878e959ca3aab1b8bfc6cdd4dbe2e9f0f7fe050c131a21282f363d444b525960676e757c838a91989fa6adb4bbc2c9d0d7dee5ecf3fa01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd040b121920272e353c434a51585f666d747b828990979ea5acb3bac1c8cfd6dde4ebf2f900";

/// `VaultHeader` equal to `new_initial()` (1, 1, 2, 4, true, 0).
const VAULT_HEADER_INITIAL_HEX: &str = "01000000010000000200000004000000010000000000000000";

/// `VaultHeader` at extremes (`u32::MAX`, 0, 7, 4, `false`, `u64::MAX`).
const VAULT_HEADER_EXTREMES_HEX: &str = "ffffffff00000000070000000400000000ffffffffffffffff";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn decode_hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("fixture hex is well-formed"))
        .collect()
}

/// The golden assertion pair: (1) `bc_serialize` must reproduce the bincode
/// 1.3.3 bytes exactly; (2) the fixture must deserialize back to an equal
/// value. Debug-format comparison stands in for `PartialEq` (these domain
/// types deliberately do not derive it).
fn assert_golden<T>(hex_fixture: &str, value: &T)
where
    T: Serialize + DeserializeOwned + std::fmt::Debug,
{
    let bytes = decode_hex(hex_fixture);
    assert_eq!(
        bc_serialize(value).expect("bc_serialize is infallible for these shapes"),
        bytes,
        "serialized bytes diverge from the bincode 1.3.3 golden fixture — \
         legacy disk-format drift, see bincode_golden.rs module docs"
    );
    let decoded: T =
        bc_deserialize(&bytes).expect("golden fixture must deserialize via bc_deserialize");
    assert_eq!(
        format!("{:?}", decoded),
        format!("{:?}", value),
        "fixture did not round-trip to an equal value"
    );
}

// ---------------------------------------------------------------------------
// Sample reconstruction (deterministic, mirrors the 1.3.3 capture run)
// ---------------------------------------------------------------------------

/// 257-byte mixed pattern: full 0x00-0xFF cycle plus one extra 0xFF.
fn long_pattern() -> Vec<u8> {
    (0..257u32).map(|i| (i * 7 % 256) as u8).collect()
}

fn sample_encrypted_data_empty() -> EncryptedData {
    EncryptedData {
        nonce: vec![],
        ciphertext: vec![],
    }
}

fn sample_encrypted_data_populated() -> EncryptedData {
    EncryptedData {
        nonce: (0u8..12).collect(),
        ciphertext: long_pattern(),
    }
}

// ---------------------------------------------------------------------------
// Golden tests — six types, two samples each
// ---------------------------------------------------------------------------

#[test]
fn encrypted_data_empty() {
    assert_golden(ENCRYPTED_DATA_EMPTY_HEX, &sample_encrypted_data_empty());
}

#[test]
fn encrypted_data_populated() {
    assert_golden(
        ENCRYPTED_DATA_POPULATED_HEX,
        &sample_encrypted_data_populated(),
    );
}

#[test]
fn password_entry_minimal() {
    let entry = PasswordEntry {
        id: String::new(),
        title: String::new(),
        url: None,
        username: String::new(),
        encrypted_password: vec![],
        encrypted_notes: None,
        tags: vec![],
        created_at: 0,
        updated_at: 0,
        last_used_at: None,
        group_id: None,
        deleted_at: None,
        encrypted_totp_secret: None,
    };
    assert_golden(PASSWORD_ENTRY_MINIMAL_HEX, &entry);
}

#[test]
fn password_entry_full_utf8() {
    let entry = PasswordEntry {
        id: "entry-uuid-日本語".to_string(),
        title: "标题-Title-🎋".to_string(),
        url: Some("https://example.com/説明".to_string()),
        username: "user@example.com".to_string(),
        encrypted_password: (0..48u8).collect(),
        encrypted_notes: Some((0..32u8).collect()),
        tags: vec![
            "work".to_string(),
            "银行".to_string(),
            "tag-with-very-long-name-for-length-coverage".to_string(),
        ],
        created_at: 1700000000,
        updated_at: 1700001234,
        last_used_at: Some(1700009999),
        group_id: Some("group-1".to_string()),
        deleted_at: Some(1700010000),
        encrypted_totp_secret: Some((0..20u8).collect()),
    };
    assert_golden(PASSWORD_ENTRY_FULL_UTF8_HEX, &entry);
}

#[test]
fn group_minimal() {
    let group = Group {
        id: String::new(),
        name: String::new(),
        created_at: 0,
        updated_at: 0,
        deleted_at: None,
    };
    assert_golden(GROUP_MINIMAL_HEX, &group);
}

#[test]
fn group_full_extremes() {
    let group = Group {
        id: "group-uuid-🎯".to_string(),
        name: "工作/个人-Bank".to_string(),
        created_at: i64::MIN,
        updated_at: 1700000000,
        deleted_at: Some(i64::MAX),
    };
    assert_golden(GROUP_FULL_EXTREMES_HEX, &group);
}

#[test]
fn settings_default() {
    assert_golden(SETTINGS_DEFAULT_HEX, &Settings::default());
}

#[test]
fn settings_extremes() {
    let settings = Settings {
        auto_lock_secs: u64::MAX,
        default_length: usize::MAX,
        default_include_uppercase: false,
        default_include_lowercase: false,
        default_include_numbers: false,
        default_include_symbols: false,
        check_updates: false,
    };
    assert_golden(SETTINGS_EXTREMES_HEX, &settings);
}

#[test]
fn verification_data_baseline() {
    let verification = VerificationData {
        salt: [0u8; 16],
        params: AdaptiveParams {
            m_cost: 65536,
            t_cost: 3,
            p_cost: 4,
        },
        encrypted_header: sample_encrypted_data_empty(),
    };
    assert_golden(VERIFICATION_DATA_BASELINE_HEX, &verification);
}

#[test]
fn verification_data_extremes() {
    let verification = VerificationData {
        salt: (0u8..16).collect::<Vec<u8>>().try_into().unwrap(),
        params: AdaptiveParams {
            m_cost: u32::MAX,
            t_cost: u32::MAX,
            p_cost: u32::MAX,
        },
        encrypted_header: sample_encrypted_data_populated(),
    };
    assert_golden(VERIFICATION_DATA_EXTREMES_HEX, &verification);
}

#[test]
fn vault_header_initial() {
    assert_golden(VAULT_HEADER_INITIAL_HEX, &VaultHeader::new_initial());
}

#[test]
fn vault_header_extremes() {
    let header = VaultHeader {
        vault_format_version: u32::MAX,
        schema_version: 0,
        record_format_version: 7,
        digest_algorithm_version: 4,
        integrity_required: false,
        migration_generation: u64::MAX,
    };
    assert_golden(VAULT_HEADER_EXTREMES_HEX, &header);
}
